export const SET_JOB_NAME = 'SET_JOB_NAME';
export const SET_JOB_SCHEDULE_TYPE = 'SET_JOB_SCHEDULE_TYPE';
export const SET_JOB_SCHEDULE_ONE_TIME_DATE = 'SET_JOB_SCHEDULE_ONE_TIME_DATE';

export const ScheduleTypes = {
  DAILY: 'DAILY',
  ONE_TIME: 'ONE_TIME',
}
